// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using Emotracker.Core;

namespace Emotracker.iOS
{
	public partial class LoginViewController : UIViewController
	{
		LoadingOverlay loadingOverlay;
		public static UIStoryboard Storyboard = UIStoryboard.FromName ("Main", null);
		public static UIViewController resultsViewController;

		public LoginService loginService = new LoginService();

		public LoginViewController() : base()
		{
		}

		public LoginViewController (IntPtr handle) : base (handle)
		{
			resultsViewController = Storyboard.InstantiateViewController("ResultsViewController") as UIViewController;
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			this.emailField.ShouldReturn += (textField) => {
				this.passwordField.BecomeFirstResponder ();
				return true;
			};

			this.passwordField.ShouldReturn += (textField) => {
				this.passwordField.ResignFirstResponder();

				doLogin();

				return true;
			};

			this.loginButton.TouchUpInside += (object sender, EventArgs e) => {
				doLogin();
			};
		}


		public void doLogin() 
		{
			this.messageView.Hidden = true;
			loadingOverlay = new LoadingOverlay (UIScreen.MainScreen.Bounds, "Signing in..");
			View.Add (loadingOverlay);

			OperationResult res = loginService.login(getLoginData());

			loadingOverlay.Hide();
			if (res.Result == false) {
				loginMessageLabel.Text = res.Message;
				messageView.Hidden = false;
			} else {
				this.PresentViewController (resultsViewController, true, null);
			}
		}

		public LoginDTO getLoginData() 
		{
			string email = this.emailField.Text;
			string pass = this.passwordField.Text;

			LoginDTO dto = new LoginDTO (email, pass);

			return dto;
		}

	}
}
