// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using Emotracker.Core;

namespace Emotracker.iOS
{
	public partial class LoginViewController : UIViewController
	{
		LoadingOverlay loadingOverlay;

		public event EventHandler InitialActionCompleted;

		public LoginViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			this.emailField.ShouldReturn += (textField) => {
				this.passwordField.BecomeFirstResponder ();
				return true;
			};

			this.passwordField.ShouldReturn += (textField) => {
				this.passwordField.ResignFirstResponder();

				doLogin();

				return true;
			};
		}

		public void doLogin() 
		{
			this.messageView.Hidden = true;
			loadingOverlay = new LoadingOverlay (UIScreen.MainScreen.Bounds, "Signing in..");
			View.Add (loadingOverlay);

			Boolean res = LoginService.login(getLoginData());

			loadingOverlay.Hide();
			if (res == false) {
				loginMessageLabel.Text = "Sorry, password is incorrect..";
				messageView.Hidden = false;
			} else {
				InitialActionCompleted.Invoke (this, new EventArgs ());
			}
		}

		public LoginDTO getLoginData() 
		{
			string email = this.emailField.Text;
			string pass = this.passwordField.Text;

			LoginDTO dto = new LoginDTO (email, pass);

			return dto;
		}

	}
}
