// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace Emotracker.iOS
{
	public partial class RegistrationViewController : UIViewController
	{
		public RegistrationViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
